name: publish

on:
  release:
    types: [released]
  # support manual release in case something goes wrong and needs to be repeated or tested
  workflow_dispatch:
    inputs:
      tag:
        description: tag that needs to publish
        type: string
        required: true
jobs:
  npm-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Release
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.githubTag }}
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.nodeVersion }}
          cache: yarn
      - run: yarn install --network-timeout 600000
      - run: yarn build
      - run: npm install --global @salesforce/plugin-release-management@3.7.3
      - run: |
          sf-release npm:package:release \
            --githubtag ${{ github.event.release.tag_name || inputs.tag || 'latest' }} \
            --npmtag ${{ inputs.tag || 'latest' }}
            --no-install
        env:
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
